// Mocks generated by Mockito 5.4.6 from annotations
// in lgbtindernew/test/unit/services/api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:lgbtindernew/core/network/dio_client.dart' as _i3;
import 'package:lgbtindernew/shared/services/cache_service.dart' as _i6;
import 'package:lgbtindernew/shared/services/connectivity_service.dart' as _i5;
import 'package:lgbtindernew/shared/services/offline_queue_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i3.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i4.Future<void> updateAuthToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateAuthToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearAuthToken() => super.noSuchMethod(
    Invocation.method(#clearAuthToken, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i5.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> waitForConnectivity({Duration? timeout}) =>
      (super.noSuchMethod(
            Invocation.method(#waitForConnectivity, [], {#timeout: timeout}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i6.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<T?> getCached<T>(
    String? key,
    T Function(Map<String, dynamic>)? fromJson, {
    Duration? customExpiry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCached,
              [key, fromJson],
              {#customExpiry: customExpiry},
            ),
            returnValue: _i4.Future<T?>.value(),
          )
          as _i4.Future<T?>);

  @override
  _i4.Future<List<T>?> getCachedList<T>(
    String? key,
    T Function(Map<String, dynamic>)? fromJson, {
    Duration? customExpiry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCachedList,
              [key, fromJson],
              {#customExpiry: customExpiry},
            ),
            returnValue: _i4.Future<List<T>?>.value(),
          )
          as _i4.Future<List<T>?>);

  @override
  _i4.Future<void> cacheData(
    String? key,
    Map<String, dynamic>? data, {
    Duration? duration = const Duration(hours: 1),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cacheData, [key, data], {#duration: duration}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cacheListData<T>(
    String? key,
    List<T>? data,
    Map<String, dynamic> Function(T)? toJson, {
    Duration? duration = const Duration(hours: 1),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cacheListData,
              [key, data, toJson],
              {#duration: duration},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCache(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearCacheByPattern(String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#clearCacheByPattern, [pattern]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isCacheValid(String? key, {Duration? customExpiry}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isCacheValid,
              [key],
              {#customExpiry: customExpiry},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [OfflineQueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineQueueService extends _i1.Mock
    implements _i7.OfflineQueueService {
  MockOfflineQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> queueRequest(_i7.QueuedRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#queueRequest, [request]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.QueuedRequest>> getQueuedRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getQueuedRequests, []),
            returnValue: _i4.Future<List<_i7.QueuedRequest>>.value(
              <_i7.QueuedRequest>[],
            ),
          )
          as _i4.Future<List<_i7.QueuedRequest>>);

  @override
  _i4.Future<void> removeRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#removeRequest, [requestId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueue, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getQueueSize() =>
      (super.noSuchMethod(
            Invocation.method(#getQueueSize, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<String> queueAction({
    required _i7.QueuedActionType? actionType,
    required String? method,
    required String? endpoint,
    Map<String, dynamic>? data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queueAction, [], {
              #actionType: actionType,
              #method: method,
              #endpoint: endpoint,
              #data: data,
              #queryParameters: queryParameters,
            }),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#queueAction, [], {
                  #actionType: actionType,
                  #method: method,
                  #endpoint: endpoint,
                  #data: data,
                  #queryParameters: queryParameters,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> syncQueue({_i2.Dio? dio}) =>
      (super.noSuchMethod(
            Invocation.method(#syncQueue, [], {#dio: dio}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.QueuedRequest>> getQueuedRequestsByType(
    _i7.QueuedActionType? actionType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQueuedRequestsByType, [actionType]),
            returnValue: _i4.Future<List<_i7.QueuedRequest>>.value(
              <_i7.QueuedRequest>[],
            ),
          )
          as _i4.Future<List<_i7.QueuedRequest>>);

  @override
  _i4.Future<void> clearRequestsByType(_i7.QueuedActionType? actionType) =>
      (super.noSuchMethod(
            Invocation.method(#clearRequestsByType, [actionType]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
