// Mocks generated by Mockito 5.4.6 from annotations
// in lgbtindernew/test/unit/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:dio/dio.dart' as _i3;
import 'package:lgbtindernew/core/network/dio_client.dart' as _i8;
import 'package:lgbtindernew/shared/models/api_response.dart' as _i2;
import 'package:lgbtindernew/shared/services/api_service.dart' as _i4;
import 'package:lgbtindernew/shared/services/token_storage_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T1> extends _i1.SmartFake
    implements _i2.ApiResponse<T1> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ApiResponse<T>> get<T>(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    T Function(dynamic)? fromJson,
    _i3.Options? options,
    bool? useCache = true,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {
                #queryParameters: queryParameters,
                #fromJson: fromJson,
                #options: options,
                #useCache: useCache,
                #forceRefresh: forceRefresh,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #get,
                  [endpoint],
                  {
                    #queryParameters: queryParameters,
                    #fromJson: fromJson,
                    #options: options,
                    #useCache: useCache,
                    #forceRefresh: forceRefresh,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> post<T>(
    String? endpoint, {
    dynamic data,
    T Function(dynamic)? fromJson,
    _i3.Options? options,
    bool? queueIfOffline = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {
                #data: data,
                #fromJson: fromJson,
                #options: options,
                #queueIfOffline: queueIfOffline,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #post,
                  [endpoint],
                  {
                    #data: data,
                    #fromJson: fromJson,
                    #options: options,
                    #queueIfOffline: queueIfOffline,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> put<T>(
    String? endpoint, {
    Map<String, dynamic>? data,
    T Function(dynamic)? fromJson,
    _i3.Options? options,
    bool? queueIfOffline = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {
                #data: data,
                #fromJson: fromJson,
                #options: options,
                #queueIfOffline: queueIfOffline,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #put,
                  [endpoint],
                  {
                    #data: data,
                    #fromJson: fromJson,
                    #options: options,
                    #queueIfOffline: queueIfOffline,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> delete<T>(
    String? endpoint, {
    Map<String, dynamic>? data,
    T Function(dynamic)? fromJson,
    _i3.Options? options,
    bool? queueIfOffline = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {
                #data: data,
                #fromJson: fromJson,
                #options: options,
                #queueIfOffline: queueIfOffline,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [endpoint],
                  {
                    #data: data,
                    #fromJson: fromJson,
                    #options: options,
                    #queueIfOffline: queueIfOffline,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> uploadFile<T>(
    String? endpoint,
    _i6.File? file, {
    String? fieldName = 'image',
    Map<String, dynamic>? fields,
    T Function(dynamic)? fromJson,
    _i3.ProgressCallback? onSendProgress,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [endpoint, file],
              {
                #fieldName: fieldName,
                #fields: fields,
                #fromJson: fromJson,
                #onSendProgress: onSendProgress,
                #options: options,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #uploadFile,
                  [endpoint, file],
                  {
                    #fieldName: fieldName,
                    #fields: fields,
                    #fromJson: fromJson,
                    #onSendProgress: onSendProgress,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);

  @override
  _i5.Future<_i2.ApiResponse<T>> uploadFiles<T>(
    String? endpoint,
    List<_i6.File>? files, {
    String? fieldName = 'images',
    Map<String, dynamic>? fields,
    T Function(dynamic)? fromJson,
    _i3.ProgressCallback? onSendProgress,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFiles,
              [endpoint, files],
              {
                #fieldName: fieldName,
                #fields: fields,
                #fromJson: fromJson,
                #onSendProgress: onSendProgress,
                #options: options,
              },
            ),
            returnValue: _i5.Future<_i2.ApiResponse<T>>.value(
              _FakeApiResponse_0<T>(
                this,
                Invocation.method(
                  #uploadFiles,
                  [endpoint, files],
                  {
                    #fieldName: fieldName,
                    #fields: fields,
                    #fromJson: fromJson,
                    #onSendProgress: onSendProgress,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.ApiResponse<T>>);
}

/// A class which mocks [TokenStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorageService extends _i1.Mock
    implements _i7.TokenStorageService {
  MockTokenStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveAuthToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveAuthToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getAuthToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveProfileCompletionToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfileCompletionToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getProfileCompletionToken() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileCompletionToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> saveRefreshToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveRefreshToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getRefreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> clearAllTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllTokens, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAuthToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthToken, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearProfileCompletionToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearProfileCompletionToken, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [DioClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioClient extends _i1.Mock implements _i8.DioClient {
  MockDioClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
          )
          as _i3.Dio);

  @override
  _i5.Future<void> updateAuthToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#updateAuthToken, [token]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearAuthToken() => super.noSuchMethod(
    Invocation.method(#clearAuthToken, []),
    returnValueForMissingStub: null,
  );
}
